START TRANSACTION ;
ALTER TABLE `Scenes` ADD COLUMN `LastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `Sessions` ADD COLUMN `LastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
COMMIT ;