<table cellspacing="0" cellpadding="0">
    <colgroup>
        <col />
        <col width="150" />
        <col width="150" />
    </colgroup>
    <thead>
        <tr>
            <th>Requirement</th>
            <th>Required</th>
            <th>Current</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->requirements as $requirement): ?>
            <tr>
                <td><div class="indicator <?php if ($requirement[3]): ?>true<?php else: ?>false<?php endif; ?>"><?php echo $this->escape($requirement[0]); ?></div></td>
                <td><?php echo $this->escape($requirement[1]); ?></td>
                <td><?php echo $this->escape($requirement[2]); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php if ($this->failure): ?>
    <p class="error">
        Not all requirements are met, please check your system settings and try again.
    </p>
<?php endif; ?>